#!/usr/bin/env bash
# Fix a nginx server to listen on port 80

# remove the default nginx configuration file
rm /etc/nginx/sites-enabled/default
# Fix nginx to listen to port 80 for all active IPv4 IPs
ln -s /etc/nginx/sites-available/default etc/nginx/sites-enabled/default
# restart nginx server
service nginx restart
