#!/usr/bin/env bash
# Configures an nginx server to listen to port 80

ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# restart nginx
service nginx start
# kill the initial nginx process ID
kill "$(pgrep 'nginx' | head -1)"
